language: node_js
node_js:
- lts/*
script:
- yarn run build
deploy:
  provider: pages
  skip_cleanup: false
  local_dir: ".vuepress/dist"
  github-token: $GITHUB_TOKEN
  keep_history: true
  on:
    branch: master
