language: node_js
node_js:
  - lts/*
script:
  - yarn run build
deploy:
  provider: pages
  email: fancyboynet@gmail.com
  skip_cleanup: true
  local_dir: .vuepress/dist
  github_token: a9e317f7b8c78cdb266eef64bd5520658dae7a87
  keep_history: true
  on:
    branch: master
