language: node_js
node_js:
- lts/*
script:
- yarn run build
deploy:
  provider: pages
  email: fancyboynet@gmail.com
  skip_cleanup: true
  local_dir: ".vuepress/dist"
  github_token: "$GITHUB_TOKEN"
  keep_history: true
  on:
    branch: master
env:
  global:
    secure: ptnO+XVhPcvHhPFAoyxymWRMbZ0BJObIMhECLKwS+2LANhVQyg0rys9CNL0fC5nCb1lGVmRumCVXKLZiTnwftiSbDw8QHBSMXdjpaiy5n8AYqsusEMEuwFAe4TrIna8X5P4HAHdpjZ2V+zvIKje432/5X9oZuJCTK8kvrxwAkALFcTosvfVa4a1q9U/dGlNIBRP/MwvBS2rw+MmsqXmbaPR3ks1eq6zd9bAjx9VSLFHetnG168O+PzNsq5g93QUgK9Oyp0EK/w0YGJKgFfu724zVEDCp/8ZTspxrTBaRqTCy8L0tEMONgP33KGM/wru2icr/dcdUpXFZ5zUv+AIZLw2mOwoQva5V0RT/44xTP/3k8kgHuGNqKrkCv8rHNcWQEQDM6Pvd4HfJgW8oJblRJ3p7+1HsabER3GMOzxirfefUOAl7c50KLES5wY2tYTI3xdVl+kBN+gRwQEEJ/kxbSnut6g2iBYM1zq/G6ObH0XQKgcIW9TmluDxRHkMsLMd5AwaisHqt+j5EysL4T6d805PpPDNWCNUhMSSFFdwn/FN+yVs7fuiqQPVZvsPCYWXgtX8n5CziJs8tb7HjVBShQ+8YelXleUAgeTWmxQBJ0BE44Bnzz/mmBsgunMg49FwoXjbVazWQPXrpo7R407PN6PNpIvzOgT1VB0pk39lneTs=
