language: node_js
node_js:
  - lts/*
script:
  - yarn run build
deploy:
  provider: pages
  email: fancyboynet@gmail.com
  skip-cleanup: true
  local_dir: .vuepress/dist
  github-token: 1f647fe903d97aff0a5f15ef19000e726eaef6c2
  keep-history: true
  on:
    branch: master
